version: '3'
services:
  vprodb:
    build: ./Dockerfile/db/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - vprodbdata:/var/lib/mysql
  
  vproapp:
    build: ./Dockerfile/app/
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: ./Dockerfile/web/
    ports:
      - "80:80"

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15671"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  vprodbdata: {}
  vproappdata: {}